name: web-jws Docker Image CI

on:
  push:
    branches: ["master"]
    paths:
      - version
      - .github/workflows/build-web-jws-docker-image.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: ./scripts/build.sh
        working-directory: ./

      - name: Push the Docker image
        run: ./scripts/push.sh
        working-directory: ./
